version: '3.3'
services:

  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    networks:
      - nesjs-network
    restart: always
  prod:
    container_name: l2b
    image: l2b:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge